name: DEPLOY

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      forced_version:
        description: 'FORCED_VERSION to use'
        required: true
        type: string

#permissions:
#  contents: write
#  discussions: write

env:
  CI: true
  FORCED_VERSION: ${{ inputs.forced_version || github.ref }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPEUSERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPEPASSWORD }}
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: zulu

jobs:
  publish:
    strategy:
      fail-fast: true # Once working, comment this
      matrix:
        include:
          - { os: ubuntu-latest, publishTask: "publishLinuxX64PublicationToMavenRepository publishLinuxArm64PublicationToMavenRepository" }
          - { os: ubuntu-latest, publishTask: "publishMingwX64PublicationToMavenRepository" }
          - { os: ubuntu-latest, publishTask: "publishAndroidDebugPublicationToMavenLocal publishAndroidReleasePublicationToMavenLocal" }
          - { os: ubuntu-latest, publishTask: "publishKotlinMultiplatformPublicationToMavenRepository publishJvmPublicationToMavenRepository" }
          - { os: ubuntu-latest, publishTask: "publishJsPublicationToMavenRepository publishWasmJsPublicationToMavenRepository" }
          - { os: macos-latest, publishTask: "publishMacosX64PublicationToMavenRepository publishMacosArm64PublicationToMavenRepository" }
          - { os: macos-latest, publishTask: "publishTvosArm64PublicationToMavenRepository publishTvosSimulatorArm64PublicationToMavenRepository publishTvosX64PublicationToMavenRepository" }
          - { os: macos-latest, publishTask: "publishIosArm64PublicationToMavenRepository publishIosSimulatorArm64PublicationToMavenRepository publishIosX64Arm64PublicationToMavenRepository" }
          - { os: macos-latest, publishTask: "publishWatchosArm64PublicationToMavenRepository publishWatchosArm32PublicationToMavenRepository publishWatchosDeviceArm64PublicationToMavenRepository publishWatchosSimulatorArm64PublicationToMavenRepository" }
    timeout-minutes: 300
    runs-on: ${{ matrix.os }}
    steps:
      - { name: Print stagedRepositoryId=$stagedRepositoryId, run: "echo 'stagedRepositoryId: $stagedRepositoryId'" }
      - { name: Checkout, uses: actions/checkout@v3 }
      - { name: Use Node.js 20.x, uses: actions/setup-node@v3, with: { node-version: 20.x } }
      - { name: Set up JDK, uses: actions/setup-java@v3, with: { distribution: "${{ env.JAVA_DISTRIBUTION }}", java-version: "${{ env.JAVA_VERSION }}" } }
      - { name: Prepare Gradle, uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 } # https://github.com/gradle/actions/releases/tag/v3.5.0
      - { name: Initialize Gradle, run: ./gradlew --no-configuration-cache }
      - { name: Start Maven Central Staging Repository, run: ./gradlew --no-configuration-cache startReleasingMavenCentral }
      - { name: Publish Publications To Maven Repository, run: "./gradlew --no-configuration-cache --parallel $publishTask" }
      - { name: Release to Maven Central, run: ./gradlew --no-configuration-cache releaseMavenCentral }
